-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 10:08:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizza_api` ;

-- -----------------------------------------------------
-- Schema pizza_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_api` DEFAULT CHARACTER SET utf8 ;
USE `pizza_api` ;

-- -----------------------------------------------------
-- Table `pizza_api`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_api`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `pizza_api`.`pizzas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `is_offer` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_api`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_api`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `pizza_api`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza_api`.`pizzas_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza_api`.`pizzas_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `pizza_api`.`pizzas_has_ingredients` (
  `pizzas_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`pizzas_id`, `ingredients_id`),
  INDEX `fk_pizzas_has_ingredients_ingredients1_idx` (`ingredients_id` ASC) VISIBLE,
  INDEX `fk_pizzas_has_ingredients_pizzas_idx` (`pizzas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_has_ingredients_pizzas`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `pizza_api`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzas_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `pizza_api`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERTION DONNEES	--
INSERT INTO ingredients (name) VALUES
('Sauce Tomate'),
('Fromage Mozzarella'),
('Pepperoni'),
('Champignons'),
('Poivron Vert'),
('Olives Noires'),
('Saucisse Italienne'),
('Oignons'),
('Basilic'),
('Ananas'),
('Jambon'),
('Feta'),
('Tomates Cerises'),
('Ail'),
('Ricotta');

INSERT INTO pizzas (name, price, is_offer) VALUES
('Margherita', 14.90, 1),
('Classique Pepperoni', 16.90, 0),
('Délice Végétarien', 15.90, 0),
('Amateurs de Viande', 18.90, 0),
('Hawaïenne', 15.40, 0),
('Poulet Pesto (Sans Sauce)', 17.90, 0),
('Festin Grec', 16.40, 0),
('Saucisse & Champignons', 17.20, 0),
('Simple Fromage', 12.90, 0),
('Suprême', 19.90, 0);

INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (1, 1), (1, 2), (1, 9), (1, 13);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (2, 1), (2, 2), (2, 3);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (3, 1), (3, 2), (3, 4), (3, 5), (3, 6), (3, 8);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (4, 1), (4, 2), (4, 3), (4, 7), (4, 11);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (5, 1), (5, 2), (5, 10), (5, 11);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (6, 2), (6, 9), (6, 15), (6, 14);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (7, 1), (7, 2), (7, 12), (7, 6), (7, 13), (7, 8);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (8, 1), (8, 2), (8, 7), (8, 4), (8, 14);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (9, 1), (9, 2);
INSERT INTO pizzas_has_ingredients (pizzas_id, ingredients_id) VALUES (10, 1), (10, 2), (10, 3), (10, 7), (10, 4), (10, 5), (10, 8), (10, 6);
